export const midiToPitch = [
  { midi: 12, pitchName: 'C0' },
  { midi: 13, pitchName: 'C#0' }, { midi: 14, pitchName: 'D0' }, { midi: 15, pitchName: 'D#0' }, { midi: 16, pitchName: 'E0' }, { midi: 17, pitchName: 'F0' }, { midi: 18, pitchName: 'F#0' }, { midi: 19, pitchName: 'G0' }, { midi: 20, pitchName: 'G#0' }, { midi: 21, pitchName: 'A0' }, { midi: 22, pitchName: 'A#0' }, { midi: 23, pitchName: 'B0' },
  { midi: 24, pitchName: 'C1' }, { midi: 25, pitchName: 'C#1' }, { midi: 26, pitchName: 'D1' }, { midi: 27, pitchName: 'D#1' }, { midi: 28, pitchName: 'E1' }, { midi: 29, pitchName: 'F1' }, { midi: 30, pitchName: 'F#1' }, { midi: 31, pitchName: 'G1' }, { midi: 32, pitchName: 'G#1' }, { midi: 33, pitchName: 'A1' }, { midi: 34, pitchName: 'A#1' }, { midi: 35, pitchName: 'B1' },
  { midi: 36, pitchName: 'C2' }, { midi: 37, pitchName: 'C#2' }, { midi: 38, pitchName: 'D2' }, { midi: 39, pitchName: 'D#2' }, { midi: 40, pitchName: 'E2' }, { midi: 41, pitchName: 'F2' }, { midi: 42, pitchName: 'F#2' }, { midi: 43, pitchName: 'G2' }, { midi: 44, pitchName: 'G#2' }, { midi: 45, pitchName: 'A2' }, { midi: 46, pitchName: 'A#2' }, { midi: 47, pitchName: 'B2' },
  { midi: 48, pitchName: 'C3' }, { midi: 49, pitchName: 'C#3' }, { midi: 50, pitchName: 'D3' }, { midi: 51, pitchName: 'D#3' }, { midi: 52, pitchName: 'E3' }, { midi: 53, pitchName: 'F3' }, { midi: 54, pitchName: 'F#3' }, { midi: 55, pitchName: 'G3' }, { midi: 56, pitchName: 'G#3' }, { midi: 57, pitchName: 'A3' }, { midi: 58, pitchName: 'A#3' }, { midi: 59, pitchName: 'B3' },
  { midi: 60, pitchName: 'C4' }, { midi: 61, pitchName: 'C#4' }, { midi: 62, pitchName: 'D4' }, { midi: 63, pitchName: 'D#4' }, { midi: 64, pitchName: 'E4' }, { midi: 65, pitchName: 'F4' }, { midi: 66, pitchName: 'F#4' }, { midi: 67, pitchName: 'G4' }, { midi: 68, pitchName: 'G#4' }, { midi: 69, pitchName: 'A4' }, { midi: 70, pitchName: 'A#4' }, { midi: 71, pitchName: 'B4' },
  { midi: 72, pitchName: 'C5' }, { midi: 73, pitchName: 'C#5' }, { midi: 74, pitchName: 'D5' }, { midi: 75, pitchName: 'D#5' }, { midi: 76, pitchName: 'E5' }, { midi: 77, pitchName: 'F5' }, { midi: 78, pitchName: 'F#5' }, { midi: 79, pitchName: 'G5' }, { midi: 80, pitchName: 'G#5' }, { midi: 81, pitchName: 'A5' }, { midi: 82, pitchName: 'A#5' }, { midi: 83, pitchName: 'B5' },
  { midi: 84, pitchName: 'C6' }, { midi: 85, pitchName: 'C#6' }, { midi: 86, pitchName: 'D6' }, { midi: 87, pitchName: 'D#6' }, { midi: 88, pitchName: 'E6' }, { midi: 89, pitchName: 'F6' }, { midi: 90, pitchName: 'F#6' }, { midi: 91, pitchName: 'G6' }, { midi: 92, pitchName: 'G#6' }, { midi: 93, pitchName: 'A6' }, { midi: 94, pitchName: 'A#6' }, { midi: 95, pitchName: 'B6' },
  { midi: 96, pitchName: 'C7' }, { midi: 97, pitchName: 'C#7' }, { midi: 98, pitchName: 'D7' }, { midi: 99, pitchName: 'D#7' }, { midi: 100, pitchName: 'E7' }, { midi: 101, pitchName: 'F7' }, { midi: 102, pitchName: 'F#7' }, { midi: 103, pitchName: 'G7' }, { midi: 104, pitchName: 'G#7' }, { midi: 105, pitchName: 'A7' }, { midi: 106, pitchName: 'A#7' }, { midi: 107, pitchName: 'B7' },
  { midi: 108, pitchName: 'C8' }, { midi: 109, pitchName: 'C#8' }, { midi: 110, pitchName: 'D8' }, { midi: 111, pitchName: 'D#8' }, { midi: 112, pitchName: 'E8' }, { midi: 113, pitchName: 'F8' }, { midi: 114, pitchName: 'F#8' }, { midi: 115, pitchName: 'G8' }, { midi: 116, pitchName: 'G#8' }, { midi: 117, pitchName: 'A8' }, { midi: 118, pitchName: 'A#8' }, { midi: 119, pitchName: 'B8' }
];